### 회원가입
POST http://luckyseven.live:10234/users/signUp
Content-Type: application/json

{
  "userName": "test1",
  "userEmail": "test@email.com",
  "userPassword": "test123???"
}

### 로그인
GET http://luckyseven.live:10234/users/singIn
Accept: application/json